//! The documentation files Debian policy requires every package to ship. Their absence is a
//! lintian error, not a warning, and blocks any repository upload.

use core::fmt::Write as _;
use std::io::Write as _;

use crate::core::plan::{BuildPlan, Destination, PlannedFile};

use crate::deb::error::{Error, Result};

const DOC_ROOT: &str = "/usr/share/doc";

/// Builds the `copyright` and compressed changelog entries for a plan.
///
/// # Errors
///
/// [`Error::Archive`] if the changelog cannot be compressed; [`Error::Core`] if a destination
/// cannot be formed, which is a defect, since the package name already passed validation.
pub fn entries(plan: &BuildPlan) -> Result<Vec<PlannedFile>> {
    let name = &plan.identity.package_name;
    let doc_dir = format!("{DOC_ROOT}/{name}");

    let copyright = Destination::new(format!("{doc_dir}/copyright")).map_err(Error::Core)?;
    let changelog =
        // `changelog.gz`, not `changelog.Debian.gz`: every package built here is native (no
        // Debian revision), and lintian names the file accordingly
        // (`wrong-name-for-changelog-of-native-package`, policy 12.7).
        Destination::new(format!("{doc_dir}/changelog.gz")).map_err(Error::Core)?;

    Ok(vec![
        PlannedFile::inline(
            copyright,
            copyright_text(plan).into_bytes(),
            PlannedFile::MODE_REGULAR,
        ),
        PlannedFile::inline(
            changelog,
            gzip(changelog_text(plan).as_bytes())?,
            PlannedFile::MODE_REGULAR,
        ),
    ])
}

/// A machine-readable copyright file, naming the licence when the manifest declared one.
fn copyright_text(plan: &BuildPlan) -> String {
    let identity = &plan.identity;
    let mut out = String::with_capacity(512);
    let _ = writeln!(
        out,
        "Format: https://www.debian.org/doc/packaging-manuals/copyright-format/1.0/"
    );
    let _ = writeln!(out, "Upstream-Name: {}", identity.package_name);
    if let Some(homepage) = &identity.homepage {
        let _ = writeln!(out, "Source: {homepage}");
    }
    out.push('\n');
    out.push_str("Files: *\n");
    // Lintian wants a notice with years (`copyright-without-copyright-notice`); the year comes
    // from the plan timestamp so two builds of one tree do not differ at New Year.
    let (year, _, _) = civil_from_days(plan.timestamp.as_secs() / 86_400);
    let _ = writeln!(out, "Copyright: {year} {}", identity.maintainer);
    match &identity.license {
        Some(license) => {
            let _ = writeln!(out, "License: {license}");
        }
        // Policy requires the field; say nothing was declared rather than invent one.
        None => out.push_str(
            "License: UNKNOWN\n \
             No license was declared. Set `license` in `.nativepkg`.\n",
        ),
    }
    out
}

/// Minimal changelog entry, dated from the plan timestamp rather than the clock.
fn changelog_text(plan: &BuildPlan) -> String {
    let identity = &plan.identity;
    format!(
        "{} ({}) unstable; urgency=medium\n\
         \n\
         \x20 * Package generated by {} {}.\n\
         \n\
         \x20-- {}  {}\n",
        identity.package_name,
        identity.version_deb,
        plan.metadata.generator,
        plan.metadata.generator_version,
        identity.maintainer,
        rfc2822(plan.timestamp.as_secs()),
    )
}

/// Debian changelog date format. Hand-rolled: `chrono` would add thirty crates for one line.
fn rfc2822(epoch: u64) -> String {
    const DAYS: [&str; 7] = ["Thu", "Fri", "Sat", "Sun", "Mon", "Tue", "Wed"];
    const MONTHS: [&str; 12] = [
        "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec",
    ];

    let days_since_epoch = epoch / 86_400;
    let seconds_of_day = epoch % 86_400;
    let (year, month, day) = civil_from_days(days_since_epoch);

    format!(
        "{}, {:02} {} {} {:02}:{:02}:{:02} +0000",
        DAYS[(days_since_epoch % 7) as usize],
        day,
        MONTHS[(month - 1) as usize],
        year,
        seconds_of_day / 3600,
        (seconds_of_day % 3600) / 60,
        seconds_of_day % 60,
    )
}

/// Howard Hinnant's `civil_from_days`: exact for the whole range, no tables.
fn civil_from_days(days: u64) -> (i64, u32, u32) {
    let z = i64::try_from(days).unwrap_or(i64::MAX) + 719_468;
    let era = z.div_euclid(146_097);
    let doe = z.rem_euclid(146_097);
    let yoe = (doe - doe / 1460 + doe / 36_524 - doe / 146_096) / 365;
    let y = yoe + era * 400;
    let doy = doe - (365 * yoe + yoe / 4 - yoe / 100);
    let mp = (5 * doy + 2) / 153;
    let d = u32::try_from(doy - (153 * mp + 2) / 5 + 1).unwrap_or(1);
    let m = u32::try_from(if mp < 10 { mp + 3 } else { mp - 9 }).unwrap_or(1);
    (if m <= 2 { y + 1 } else { y }, m, d)
}

fn gzip(input: &[u8]) -> Result<Vec<u8>> {
    // Policy 12.3 requires `gzip -9` for changelogs; lintian reports less as
    // `changelog-not-compressed-with-max-compression`.
    let mut encoder = flate2::write::GzEncoder::new(Vec::new(), flate2::Compression::best());
    encoder
        .write_all(input)
        .map_err(|e| Error::archive("could not compress the changelog", e))?;
    encoder
        .finish()
        .map_err(|e| Error::archive("could not compress the changelog", e))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::deb::test_support::sample_plan;

    #[test]
    fn both_policy_required_files_are_produced() {
        let entries = entries(&sample_plan()).expect("should build");
        let paths: Vec<&str> = entries.iter().map(|e| e.destination.as_str()).collect();
        assert!(
            paths.contains(&"/usr/share/doc/probe-app/copyright"),
            "{paths:?}"
        );
        assert!(
            paths.contains(&"/usr/share/doc/probe-app/changelog.gz"),
            "{paths:?}"
        );
    }

    #[test]
    fn the_changelog_is_actually_gzipped() {
        let entries = entries(&sample_plan()).expect("should build");
        let changelog = entries
            .iter()
            .find(|e| e.destination.as_str().ends_with("changelog.gz"))
            .expect("changelog present");
        let bytes = match &changelog.content {
            crate::core::plan::FileContent::Inline(b) => b,
            other => panic!("expected inline content, got {other:?}"),
        };
        assert_eq!(&bytes[..2], &[0x1f, 0x8b], "not a gzip stream");
    }

    #[test]
    fn the_copyright_names_the_declared_licence() {
        let entries = entries(&sample_plan()).expect("should build");
        let text = inline_text(&entries, "copyright");
        assert!(text.contains("License: MIT"), "{text}");
    }

    #[test]
    fn a_missing_licence_is_stated_rather_than_invented() {
        let mut plan = sample_plan();
        plan.identity.license = None;
        let entries = entries(&plan).expect("should build");
        let text = inline_text(&entries, "copyright");
        assert!(text.contains("UNKNOWN"), "{text}");
        assert!(
            text.contains(".nativepkg"),
            "should say how to fix it: {text}"
        );
    }

    /// Through `entries()`: the formatter tests pin fixed epochs, so they stayed green when
    /// `changelog_text` was handed a constant instead of the plan's timestamp.
    #[test]
    fn the_shipped_changelog_carries_the_plan_timestamp() {
        use std::io::Read as _;

        let plan = sample_plan();
        let entries = entries(&plan).expect("should build");
        let changelog = entries
            .iter()
            .find(|e| e.destination.as_str().ends_with("changelog.gz"))
            .expect("changelog present");
        let gz = match &changelog.content {
            crate::core::plan::FileContent::Inline(b) => b,
            other => panic!("expected inline content, got {other:?}"),
        };

        let mut text = String::new();
        flate2::read::GzDecoder::new(&gz[..])
            .read_to_string(&mut text)
            .expect("the changelog should decompress");

        let expected = rfc2822(plan.timestamp.as_secs());
        assert!(
            text.contains(&expected),
            "changelog should carry the plan's date `{expected}`:\n{text}"
        );
        assert!(text.contains(&plan.identity.package_name), "{text}");
        assert!(text.contains(&plan.identity.version_deb), "{text}");
        assert!(text.contains(&plan.identity.maintainer), "{text}");
    }

    #[test]
    fn the_changelog_date_comes_from_the_plan_not_the_clock() {
        // 2023-11-14T22:13:20Z
        assert_eq!(rfc2822(1_700_000_000), "Tue, 14 Nov 2023 22:13:20 +0000");
        assert_eq!(rfc2822(0), "Thu, 01 Jan 1970 00:00:00 +0000");
    }

    #[test]
    fn dates_are_correct_across_leap_years_and_century_boundaries() {
        assert_eq!(&rfc2822(951_782_400)[..16], "Tue, 29 Feb 2000");
        assert_eq!(&rfc2822(1_709_164_800)[..16], "Thu, 29 Feb 2024");
        assert_eq!(&rfc2822(1_735_689_600)[..16], "Wed, 01 Jan 2025");
    }

    fn inline_text(entries: &[PlannedFile], suffix: &str) -> String {
        let entry = entries
            .iter()
            .find(|e| e.destination.as_str().ends_with(suffix))
            .expect("entry present");
        match &entry.content {
            crate::core::plan::FileContent::Inline(b) => String::from_utf8_lossy(b).into_owned(),
            other => panic!("expected inline content, got {other:?}"),
        }
    }
}
