[package]
name = "nativepkg-cli"
description = "Command line interface for nativepkg"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[lib]
name = "nativepkg_cli"
path = "src/lib.rs"

[[bin]]
name = "nativepkg"
path = "src/main.rs"

[dependencies]
nativepkg-core.workspace = true
nativepkg-deb.workspace = true
nativepkg-rpm.workspace = true
nativepkg-arch.workspace = true
anyhow.workspace = true
clap.workspace = true
serde_json.workspace = true

[dev-dependencies]
zstd.workspace = true
tar.workspace = true
rpm.workspace = true

[lints]
workspace = true
