//! The `.PKGINFO` member: Arch's package metadata.
//!
//! Format taken from decoding a real package (`openspec/arch-format.md`). Two details differ
//! from Debian and matter: `pkgver` joins version and release with a hyphen, which is why the
//! version itself may not contain one; and `size` is bytes, not kibibytes as `Installed-Size` is.

use core::fmt::Write as _;

use nativepkg_core::plan::{BuildPlan, EntryKind, PlannedFile};

/// Marks an ordinary package, as opposed to a split or debug one.
const PACKAGE_TYPE: &str = "pkgtype=pkg";

#[must_use]
pub fn render(plan: &BuildPlan, generator: &str) -> String {
    let identity = &plan.identity;
    let mut out = String::with_capacity(512);

    let _ = writeln!(out, "# Generated by {generator}");
    let _ = writeln!(out, "pkgname = {}", identity.package_name);
    let _ = writeln!(out, "pkgbase = {}", identity.package_name);
    let _ = writeln!(out, "xdata = {PACKAGE_TYPE}");
    let _ = writeln!(
        out,
        "pkgver = {}",
        pkgver(&identity.version_rpm, &identity.release_rpm, identity.epoch)
    );
    let _ = writeln!(out, "pkgdesc = {}", identity.description.synopsis);
    if let Some(homepage) = &identity.homepage {
        let _ = writeln!(out, "url = {homepage}");
    }
    let _ = writeln!(out, "builddate = {}", plan.timestamp.as_secs());
    let _ = writeln!(out, "packager = {}", identity.maintainer);
    let _ = writeln!(out, "size = {}", installed_bytes(plan));
    let _ = writeln!(out, "arch = {}", identity.architecture.arch_linux());
    if let Some(license) = &identity.license {
        let _ = writeln!(out, "license = {license}");
    }
    for name in dependency_names(identity.dependencies.as_deref()) {
        let _ = writeln!(out, "depend = {name}");
    }
    for file in plan.config_files() {
        // Arch calls config files backup paths, recorded without the leading `/`.
        let _ = writeln!(out, "backup = {}", file.destination.relative_str());
    }
    out
}

/// Arch's single `pkgver` field; an epoch is a `N:` prefix, as in Debian.
#[must_use]
pub fn pkgver(version: &str, release: &str, epoch: Option<u32>) -> String {
    match epoch {
        Some(epoch) => format!("{epoch}:{version}-{release}"),
        None => format!("{version}-{release}"),
    }
}

fn installed_bytes(plan: &BuildPlan) -> u64 {
    plan.files
        .iter()
        .filter(|file| file.kind == EntryKind::Regular)
        .map(|file| file.content.len())
        .sum()
}

/// Splits a Debian-spelling dependency list into bare names. Only names travel, as in the RPM
/// backend; dropping `nodejs (>= 18)` widens the requirement, and translating it is separate.
fn dependency_names(expression: Option<&str>) -> Vec<String> {
    expression
        .unwrap_or_default()
        .split(',')
        .filter_map(|entry| {
            let name = entry
                .split('(')
                .next()
                .unwrap_or_default()
                .split('|')
                .next()
                .unwrap_or_default()
                .trim();
            (!name.is_empty()).then(|| name.to_owned())
        })
        .collect()
}

/// Every declared value for `key`, in order; `.PKGINFO` repeats keys, so one value would hide
/// dependencies. For tests.
#[must_use]
pub fn values<'a>(rendered: &'a str, key: &str) -> Vec<&'a str> {
    rendered
        .lines()
        .filter_map(|line| line.split_once(" = "))
        .filter(|(k, _)| *k == key)
        .map(|(_, v)| v)
        .collect()
}

/// Whether the plan ships no regular file, so an empty package does not claim a size.
#[must_use]
pub fn is_empty(plan: &BuildPlan) -> bool {
    !plan.files.iter().any(PlannedFile::is_regular)
}
